### ISSUE TITLE
[Bug] MockActivityEnvironment holds open handle prevents jest from exiting

### ISSUE THREAD

**Issue by shawnjones253** [temporalio/sdk-typescript#1259] opened 2023-10-12 03:15 UTC
### What are you really trying to do?

Run a temporal activity within a jest test.

### Describe the bug

Jest can't exit after instantiating MockActivityEnvironment, even if I don't actually use the MockActivityEnvironment to run an activity.

### Minimal Reproduction

```
test('some test', async () => {
  const env = new MockActivityEnvironment()
  // whether or not you use env.run() doesn't seem to matter...
}
```

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  neon threadsafe function

      261 |
      262 |   test('some test', async () => {
    > 263 |     const env = new MockActivityEnvironment()
          |                 ^

 at ../../node_modules/@temporalio/core-bridge/index.js:16:14
      at Function.create (../../node_modules/@temporalio/worker/src/runtime.ts:208:31)
      at Function.instance (../../node_modules/@temporalio/worker/src/runtime.ts:196:17)
      at new MockActivityEnvironment (../../node_modules/@temporalio/testing/src/index.ts:413:15)
```
### Environment/Versions

- OS and processor: M1 Mac
- Temporal Version: 1.8.1
- Are you using Docker or Kubernetes or building Temporal from source? No

**Comment by mjameswh** [comment] 2023-10-12 20:33
Duplicate of #928

**Closed by mjameswh** 2023-10-12 20:33 UTC
Labels: bug
