### ISSUE TITLE
[Bug] log.error doesn't log the error

### ISSUE THREAD

**Issue by shawnjones253** [temporalio/sdk-typescript#1491] opened 2024-08-13 17:56 UTC
### What are you really trying to do?

I want to use the '@temporalio/workflow' `log.error(message: string, attrs?: Record<string, unknown>): void` method within an interceptor to log `Error` objects.

### Describe the bug

Create a `WorkflowStatusInterceptor`. Run a workflow that uses `continueAsNew` to generate an error for the interceptor:

```
import { log, Next, WorkflowExecuteInput, WorkflowInboundCallsInterceptor } from '@temporalio/workflow'

export class WorkflowStatusInterceptor
  implements WorkflowInboundCallsInterceptor
{
  constructor() {}

  public async execute(
    input: WorkflowExecuteInput,
    next: Next<WorkflowInboundCallsInterceptor, 'execute'>
  ): Promise<unknown> {
    try {
        const ret = await next(input)
        return ret
    } catch (e) { // upon catching ContinueAsNew error
            log.error('shouldLogContinueAsNewError', e) // all properties of `e` are missing from this log!
            log.error(e.name) // prints ContinueAsNew
            log.error((e instanceof Error).toString()) // prints true
    }
  }
}
```

```
// note this first log is missing all properties of the actual error!
2024-08-06T20:43:23.561Z [ERROR] shouldLogContinueAsNewError {
  sdkComponent: 'workflow',
  taskQueue: 'my-queue',
  namespace: 'default',
  workflowId: my-wf-id',
  runId: '1b4076e7-a5a7-4ac0-9e8c-1acedb9401a3',
  workflowType: 'my-wf-type',
  command: {
    workflowType: 'my-wf-type',
    arguments: [ [Object] ],
    headers: {},
    taskQueue: 'my-queue',
    memo: undefined,
    searchAttributes: undefined,
    workflowRunTimeout: undefined,
    workflowTaskTimeout: undefined,
    versioningIntent: 0
  }
}

2024-08-06T20:43:23.561Z [ERROR] ContinueAsNew {
  sdkComponent: 'workflow',
  taskQueue: 'my-queue',
  namespace: 'default',
  workflowId: my-wf-id',
  runId: '1b4076e7-a5a7-4ac0-9e8c-1acedb9401a3',
  workflowType: 'my-wf-type'
}

2024-08-06T20:43:23.561Z [ERROR] true {
  sdkComponent: 'workflow',
  taskQueue: 'my-queue',
  namespace: 'default',
  workflowId: my-wf-id',
  runId: '1b4076e7-a5a7-4ac0-9e8c-1acedb9401a3',
  workflowType: 'my-wf-type'
}
```

### Environment/Versions

- OS and processor: M1 mac
- Temporal Version: 1.10.1 (sdk)
- Are you using Docker or Kubernetes or building Temporal from source? `temporalio/auto-setup:1.23.1` via docker

### Additional context

Why it matters, this makes it hard to figure out what errors I need to catch in my interceptor without creating support threads:
https://community.temporal.io/t/any-way-to-get-notified-or-execute-callback-for-change-in-workflowexecutionstatus/12297/11?u=shawn_jones

**Comment by mjameswh** [comment] 2024-09-09 15:16
Duplicate of #1274.

**Closed by mjameswh** 2024-09-09 15:16 UTC
Labels: bug
