### ISSUE TITLE
[Bug] jest times-out on first run of TestWorkflowEnvironment

### ISSUE THREAD

**Issue by joebowbeer** [temporalio/sdk-typescript#728] opened 2022-06-27 20:40 UTC
### What are you really trying to do?

Unit testing workflow using jest and TestWorkflowEnvironment

### Describe the bug

jest is likely to timeout the first time I run the tests

### Minimal Reproduction

```bash
git checkout https://github.com/temporal/temporal-pendulum
cd position-node
nvm use
npm i
npm t
```

On the first run, I see timeout failures:

```
  2022-06-27T20:13:26.565908Z  WARN temporal_sdk_core::worker::workflow: Task not found when completing, error: status: NotFound, message: "Completed workflow", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, run_id: "5d3c6943-1da7-43ab-b5cf-344429e4fa4a"
```

  ✕ pendulum exitSignal (5006 ms)
  ✕ pendulum getGameInfoQuery (1575 ms)
  ✓ pendulum updateGameInfoSignal (323 ms)

![fail](https://user-images.githubusercontent.com/28679/176031519-e5b19ab7-51a2-48bf-9a6c-3699ddfbb886.png)

The next time it usually passes:

  ✓ pendulum exitSignal (839 ms)
  ✓ pendulum getGameInfoQuery (338 ms)
  ✓ pendulum updateGameInfoSignal (312 ms)

![pass](https://user-images.githubusercontent.com/28679/176031542-304f72ff-6982-48e6-abd2-0221327856ee.png)

### Environment/Versions

M1 Mac
@temporal/testing 1.0.0-rc.0 
Node 16.15.1

### Additional context

Is there a race starting the test env?
Is there a timeout I can/should increase?

**Comment by vkarpov15** [comment] 2022-07-11 00:40
@joebowbeer I'm unable to repro this on either my mac or my linux box. For example, below is my output running `npm test` on temporal-pendulum after a clean install:

```
$ npm test

> position-node@0.2.0 test /Users/val/Workspace/temporalio/temporal-pendulum/position-node
> NODE_OPTIONS=--experimental-vm-modules jest

(node:26895) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

 RUNS  src/workflows.test.ts
  2022-07-11T00:26:28.902615Z  WARN temporal_sdk_core::worker::workflow::workflow_stream: WFT poller died, shutting down
 RUNS  src/workflows.test.ts
  2022-07-11T00:26:30.480330Z  WARN temporal_sdk_core::worker::workflow::workflow_stream: WFT poller died, shutting down
 RUNS  src/workflows.test.ts
  2022-07-11T00:26:31.970849Z  WARN temporal_sdk_core::worker::workflow::workflow_stream: WFT poller d PASS  src/workflows.test.ts (15.569 s)
  ✓ gameInfo without overrides (2 ms)
  ✓ gameInfo with overrides (1 ms)
  ✓ pendulum exitSignal (3733 ms)
  ✓ pendulum getGameInfoQuery (1570 ms)
  ✓ pendulum updateGameInfoSignal (1493 ms)

--------------|---------|----------|---------|---------|-------------------
File          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------|---------|----------|---------|---------|-------------------
All files     |   51.72 |      100 |       0 |   51.72 |                   
 workflows.ts |   51.72 |      100 |       0 |   51.72 | 29-56             
--------------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        15.808 s
Ran all test suites.
$ npm test

> position-node@0.2.0 test /Users/val/Workspace/temporalio/temporal-pendulum/position-node
> NODE_OPTIONS=--experimental-vm-modules jest

(node:26920) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

 RUNS  src/workflows.test.ts
  2022-07-11T00:26:49.897900Z  WARN temporal_sdk_core::worker::workflow::workflow_stream: WFT poller died, shutting down
 RUNS  src/workflows.test.ts
  2022-07-11T00:26:51.311469Z  WARN temporal_sdk_core::worker::workflow::workflow_stream: WFT poller died, shutting down
 RUNS  src/workflows.test.ts
  2022-07-11T00:26:52.602291Z  WARN temporal_sdk_core::worker::workflow::workflow_stream: WFT poller d PASS  src/workflows.test.ts (14.429 s)
  ✓ gameInfo without overrides (3 ms)
  ✓ gameInfo with overrides
  ✓ pendulum exitSignal (3622 ms)
  ✓ pendulum getGameInfoQuery (1417 ms)
  ✓ pendulum updateGameInfoSignal (1288 ms)

--------------|---------|----------|---------|---------|-------------------
File          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------|---------|----------|---------|---------|-------------------
All files     |   51.72 |      100 |       0 |   51.72 |                   
 workflows.ts |   51.72 |      100 |       0 |   51.72 | 29-56             
--------------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        14.718 s, estimated 16 s
Ran all test suites.
$ 
$ 
$ 
$ npm test

> position-node@0.2.0 test /Users/val/Workspace/temporalio/temporal-pendulum/position-node
> NODE_OPTIONS=--experimental-vm-modules jest

(node:27004) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

 RUNS  src/workflows.test.ts
  2022-07-11T00:28:28.392233Z  WARN temporal_sdk_core::worker::workflow::workflow_stream: WFT poller died, shutting down
 RUNS  src/workflows.test.ts
  2022-07-11T00:28:29.883512Z  WARN temporal_sdk_core::worker::workflow::workflow_stream: WFT poller died, shutting down
 RUNS  src/workflows.test.ts
  2022-07-11T00:28:31.279849Z  WARN temporal_sdk_core::worker::workflow::workflow_stream: WFT poller d PASS  src/workflows.test.ts (14.787 s)
  ✓ gameInfo without overrides (2 ms)
  ✓ gameInfo with overrides
  ✓ pendulum exitSignal (3706 ms)
  ✓ pendulum getGameInfoQuery (1488 ms)
  ✓ pendulum updateGameInfoSignal (1477 ms)

--------------|---------|----------|---------|---------|-------------------
File          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------|---------|----------|---------|---------|-------------------
All files     |   51.72 |      100 |       0 |   51.72 |                   
 workflows.ts |   51.72 |      100 |       0 |   51.72 | 29-56             
--------------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        15.109 s
Ran all test suites.
$ 
```

The tests are slow, but seem to work. Couple of potential explanations:

1. Can you try increasing the test timeout using `jest.setTimeout(15000)`? 
2. All the examples in the [testing docs](https://docs.temporal.io/typescript/testing) use `execute()` instead of `start()`, because [`start()` starts the workflow in "normal time" as opposed to "skipped time". Maybe worthwhile to try using the [pattern I use in temporal-ecommerce-ts for testing queries and signals](https://github.com/vkarpov15/temporal-ecommerce-ts/blob/95b7be70d0b2a8d95cea93ec719453c94fa68f2e/src/test/workflows.test.ts#L65-L80) rather than `runUntil()`?

**Comment by joebowbeer** [comment] 2022-07-11 05:42
@vkarpov15 wrote:

> The tests are slow, but seem to work.

> Can you try increasing the test timeout using jest.setTimeout(15000)?

Thanks for looking into it. I'll play with jest's `testTimeout` next time I have an opportunity. This can be configured in `jest.config.js`. However, I just tried to repro in GitPod and I'm not seeing the timeout at the moment.

> All the examples in the [testing docs](https://docs.temporal.io/typescript/testing) use execute() instead of start(), because https://github.com/temporalio/documentation/pull/1252. Maybe worthwhile to try using the [pattern I use in temporal-ecommerce-ts for testing queries and signals](https://github.com/vkarpov15/temporal-ecommerce-ts/blob/95b7be70d0b2a8d95cea93ec719453c94fa68f2e/src/test/workflows.test.ts#L65-L80) rather than runUntil()?

I use `start` because this workflow does not complete until it is signaled.

Thanks for showing me the pattern. LGTM but I don't like that each test leaves a dangling workflow (right?). It would be more hermetic for `afterEach` to complete the workflow.

**Comment by bergundy** [comment] 2022-07-12 03:11
@vkarpov15 you can still use runUntil, although if you have multiple tests in the same file each creating their own worker I’d suggest bundling the workflows once during setup because that could take up a lot of resources

**Comment by bergundy** [comment] 2022-07-12 03:12
I generally wouldn’t recommend leaving dangling workflows around in tests but it’s okayish when using the ephemeral test server

**Comment by bergundy** [comment] 2022-10-03 13:08
We’ve redone the test framework in 1.3.0. And haven’t been able to reproduce this, closing until this is reproducible.

**Closed by bergundy** 2022-10-03 13:08 UTC
Labels: bug
