### ISSUE TITLE
[Bug] `stress-tests` may time out

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#913] opened 2022-10-10 22:34 UTC
[stress-tests / stress-test](https://github.com/temporalio/sdk-typescript/actions/runs/3222639386/jobs/5271917118#logs)

seemed stuck on 

```
WFs complete (9940/10000)
```

**Comment by lorensr** [comment] 2022-10-10 23:26
second run seemed stuck on:

```
WFs complete (63/100)
```

[stress-tests / stress-test](https://github.com/temporalio/sdk-typescript/actions/runs/3222639386/jobs/5272202180#logs)

**Comment by bergundy** [comment] 2022-10-10 23:28
It's a known issue, we need to fix the stress test to recycle the instance every once in a while.

**Comment by mjameswh** [comment] 2022-10-13 11:49
Duplicate of #853

**Closed by mjameswh** 2022-10-13 11:49 UTC
Labels: bug, duplicate, ci flake
