### ISSUE TITLE
[Bug] `npm i --production` insufficient

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-typescript#489] opened 2022-02-17 23:15 UTC
@idoshamun reported in https://github.com/temporalio/documentation/pull/917 that they needed to `npm i` instead of `npm i --production` (or `npm i --only=prod` or `NODE_ENV=production npm i`), which implies that we need to move at least one devDep to deps somewhere. I haven't repro'd yet. Ido—do you have the error message, or remember which package it was in?

**Comment by idoshamun** [comment] 2022-02-18 07:08
Here it is:
```
2022-02-15T20:51:37.521Z [INFO] [temporal_sdk_core] Registering worker task_queue="content-pipeline"
Error: Cannot find module 'acorn'
Require stack:
- /opt/app/node_modules/acorn-import-assertions/lib/index.js
- /opt/app/node_modules/webpack/lib/javascript/JavascriptParser.js
- /opt/app/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js
- /opt/app/node_modules/webpack/lib/WebpackOptionsApply.js
- /opt/app/node_modules/webpack/lib/webpack.js
- /opt/app/node_modules/webpack/lib/index.js
- /opt/app/node_modules/@temporalio/worker/lib/workflow/bundler.js
- /opt/app/node_modules/@temporalio/worker/lib/worker.js
- /opt/app/node_modules/@temporalio/worker/lib/index.js
- /opt/app/src/temporal/worker.js
- /opt/app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/app/node_modules/acorn-import-assertions/lib/index.js:8:38)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/app/node_modules/acorn-import-assertions/lib/index.js',
    '/opt/app/node_modules/webpack/lib/javascript/JavascriptParser.js',
    '/opt/app/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js',
    '/opt/app/node_modules/webpack/lib/WebpackOptionsApply.js',
    '/opt/app/node_modules/webpack/lib/webpack.js',
    '/opt/app/node_modules/webpack/lib/index.js',
    '/opt/app/node_modules/@temporalio/worker/lib/workflow/bundler.js',
    '/opt/app/node_modules/@temporalio/worker/lib/worker.js',
    '/opt/app/node_modules/@temporalio/worker/lib/index.js',
    '/opt/app/src/temporal/worker.js',
    '/opt/app/index.js'
  ]
}
```

**Comment by idoshamun** [comment] 2022-02-20 14:10
Following James Watkins-Harvey advice on Slack (https://temporalio.slack.com/archives/CTRCR8RBP/p1645195758175629?thread_ts=1644943893.749649&cid=CTRCR8RBP), I managed to find the root cause.
I used `workflowsPath` instead of `workflowBundle` which caused temporal to build my workflows in production.

I somehow missed the point here:
https://docs.temporal.io/docs/typescript/production-deploy#pre-build-code

I think we can close this issue now.

**Comment by mjameswh** [comment] 2022-02-21 18:46
@idoshamun Glad it helped.

It might still be useful though to highlight this point in documentation. Using `workflowsPath` is essentially a "development mode", and implies that you need to install development dependencies.

Along the same line, it could be useful to make the dependency from @temporalio/worker to webpack a dev-dependency (see [here](https://github.com/temporalio/sdk-typescript/blob/817312d4059200c2c15a608282d159ad51679915/packages/worker/package.json#L35)). It would be much easier for people to understand the situation when they get a message saying they're missing webpack than some less known package down the road.

**Comment by idoshamun** [comment] 2022-02-22 08:56
@mjameswh you're right.
See my PR here: https://github.com/temporalio/documentation/pull/930
Hopefully it will get reviewed and merged soon

**Comment by lorensr** [comment] 2022-02-22 21:57
We'd like `workflowsPath` to work in prod, so let's add acorn and whatever else we need. 

My repro gives this output:

```
git clone https://github.com/temporalio/samples-typescript
cd samples-typescript/hello-world
npm i --production
npm run build
node lib/worker.js
```

```
2022-02-22T21:40:25.170Z [ERROR] ERROR in ./node_modules/@temporalio/common/lib/time.js 8:29-42
2022-02-22T21:40:25.170Z [ERROR] Module not found: Error: Can't resolve 'ms' in '/Users/me/gh/samples-typescript/hello-world/node_modules/@temporalio/common/lib'
2022-02-22T21:40:25.170Z [ERROR] resolve 'ms' in '/Users/me/gh/samples-typescript/hello-world/node_modules/@temporalio/common/lib'
2022-02-22T21:40:25.170Z [ERROR]   Parsed request is a module
2022-02-22T21:40:25.170Z [ERROR]   using description file: /Users/me/gh/samples-typescript/hello-world/node_modules/@temporalio/common/package.json (relative path: ./lib)
2022-02-22T21:40:25.170Z [ERROR]     Field 'browser' doesn't contain a valid alias configuration
2022-02-22T21:40:25.170Z [ERROR]     resolve as module
2022-02-22T21:40:25.170Z [ERROR]       looking for modules in /Users/me/gh/samples-typescript/hello-world/node_modules
2022-02-22T21:40:25.170Z [ERROR]         single file module
2022-02-22T21:40:25.170Z [ERROR]           using description file: /Users/me/gh/samples-typescript/hello-world/package.json (relative path: ./node_modules/ms)
2022-02-22T21:40:25.170Z [ERROR]             no extension
2022-02-22T21:40:25.170Z [ERROR]               Field 'browser' doesn't contain a valid alias configuration
2022-02-22T21:40:25.170Z [ERROR]               /Users/me/gh/samples-typescript/hello-world/node_modules/ms doesn't exist
2022-02-22T21:40:25.170Z [ERROR]             .ts
2022-02-22T21:40:25.170Z [ERROR]               Field 'browser' doesn't contain a valid alias configuration
2022-02-22T21:40:25.170Z [ERROR]               /Users/me/gh/samples-typescript/hello-world/node_modules/ms.ts doesn't exist
2022-02-22T21:40:25.170Z [ERROR]             .js
2022-02-22T21:40:25.170Z [ERROR]               Field 'browser' doesn't contain a valid alias configuration
2022-02-22T21:40:25.170Z [ERROR]               /Users/me/gh/samples-typescript/hello-world/node_modules/ms.js doesn't exist
2022-02-22T21:40:25.170Z [ERROR]         /Users/me/gh/samples-typescript/hello-world/node_modules/ms doesn't exist
2022-02-22T21:40:25.170Z [ERROR]  @ ./node_modules/@temporalio/common/lib/index.js 25:13-30
2022-02-22T21:40:25.170Z [ERROR]  @ ./node_modules/@temporalio/workflow/lib/worker-interface.js 9:17-46
2022-02-22T21:40:25.170Z [ERROR]  @ ../../../../../src/main.js 1:0-68 4:0-19 5:0-18 16:0-15
2022-02-22T21:40:25.170Z [ERROR] 
2022-02-22T21:40:25.170Z [ERROR] webpack 5.69.1 compiled with 1 error in 373 ms
Error: Webpack finished with errors, if you're unsure what went wrong, visit our troubleshooting page at https://docs.temporal.io/docs/typescript/troubleshooting#webpack-errors
```

`ms` is a dep of `@temporalio/common`:

<img width="724" alt="image" src="https://user-images.githubusercontent.com/251288/155225608-8a77cbed-a161-46b0-9785-9e9173d1b171.png">

But it doesn't appear in `node_modules/ms` until I run `npm i` (without --production).

Not sure when I'll get to this, but happy to review a PR if anyone would like to contribute! 😊

**Comment by mjameswh** [comment] 2022-02-23 13:38
I was wrong. Acorn is a regular dependency of webpack, not a dev dependency. The problem isn't there.

But let's focus on the issue with `ms` for now. With `npm i`, I get the following copies of `ms`:

```
node_modules/@temporalio/client/node_modules/ms
node_modules/@temporalio/common/node_modules/ms
node_modules/@temporalio/worker/node_modules/ms
node_modules/ms
```

But with `npm i --production`, I get only get the followings:

```
node_modules/@temporalio/client/node_modules/ms
node_modules/@temporalio/common/node_modules/ms
node_modules/@temporalio/worker/node_modules/ms
```

So npm hoisted `ms` from some development package in the first case (actually, from `nodemon -> debug -> ms`), but didn't dedup `ms` (because `debug@4.3.3` require exact version `ms@2.1.2`, which is incompatible with requirement `ms@^2.1.3` from `@temporalio/common`). Now, when giving `--production`, npm actually calculates its ideal dependency tree including _all_ dependencies (ie. including dev and optional dependencies), then prune (if requested) dev and optional dependencies at a very late stage. That explains why `ms` is not getting hoisted/dedup with `npm i --production`.

One way or another, both are valid given Node's module resolution algorithm. It isn't working with our webpack bundler, however, because our default value for `resolve.modules` only includes absolute (see [here](https://github.com/temporalio/sdk-typescript/blob/fba4d46b668ef9b0feec0d953b359ab10adb9e01/packages/worker/src/workflow/bundler.ts#L106-L108) and  [here](https://github.com/temporalio/sdk-typescript/blob/fba4d46b668ef9b0feec0d953b359ab10adb9e01/packages/worker/src/worker-options.ts#L295-L299)). To get webpack to resolve dependencies using an algorithm compatible with Node's algorithm, we must also include the string  'node_modules' in `resolve.modules`.

For example, if I manually specify `nodeModulesPaths` in `hello-world/src/worker.ts`, _and add 'node_modules' to the array_, as follow:

```
  const worker = await Worker.create({
    workflowsPath: require.resolve('./workflows'),
    nodeModulesPaths: [`${__dirname}/../node_modules/`, 'node_modules'],
    activities,
    taskQueue: 'tutorial',
  });
```

then I no longer have any issue executing after `npm i --production`. Turns out that the missing `acorn` was similarly hiding inside `node_modules/webpack/node_modules/acorn`, there again because of a version incompatibility between a dev dependency and a runtime dependency.

So we simply add `node_modules` to the provided `nodeModulesPaths`, and voilà! I shall submit a PR for this soon.

**Closed** 2022-02-24 23:33 UTC
Labels: bug
