### ISSUE TITLE
[Bug] Memory leak on the temporal worker side(OperatorSubscriber Class Objects are taking much of the memory)

### ISSUE THREAD

**Issue by jainshivsagar** [temporalio/sdk-typescript#1541] opened 2024-10-08 07:39 UTC
### What are you really trying to do?

We are using the TypeScript SDK v1.9.0 for our temporal worker.
We are doing the load testing in the local System. At the start of the worker the Memory(or Heap) utilization was <120MB, post the load testing, the Memory(or Heap) increased to ~300MB. After 5-10 minutes of load testing the memory utilization didn't come down.
Please refer to the below screenshots of Chrome DevTool(Memory Profiler):-

Memory Utilization after starting the worker:-

![image](https://github.com/user-attachments/assets/22394454-9cbe-4fa2-8aef-581f0ec32418)

Memory Utilization after load testing:-
![image](https://github.com/user-attachments/assets/f8cb4fc1-319b-4fbb-aae3-463f42bb1458)

Comparison of first two Heap snapshots:-
![image](https://github.com/user-attachments/assets/c304481c-e0e0-414f-96f7-aff0ef22295a)

### Environment/Versions

- OS and processor: 2.6 GHz 6-Core Intel Core i7, MacOs Sequoia(v15.0.1)
- Temporal Version: Temporal TypeScript SDK v1.9.0
- We running the worker in K8 nodes on the Staging/Prod ENV.

### Worker Configurations:-
```
  const worker = await Worker.create({
    connection,
    namespace: config.Temporal.Namespace,
    taskQueue: config.Temporal.TaskQueue,
    workflowsPath: require.resolve('./workflows'),
    activities: getActivities(),
    // maxActivitiesPerSecond: 100,
    // maxTaskQueueActivitiesPerSecond: 100,
    // maxConcurrentActivityTaskExecutions: 2000,
    maxConcurrentWorkflowTaskExecutions: 200,
    maxConcurrentWorkflowTaskPolls: 100,
    // maxConcurrentActivityTaskPolls: 1000,
    // maxCachedWorkflows: 3000,
    maxConcurrentLocalActivityExecutions: 200,
    // workflowThreadPoolSize: 100,
    enableNonLocalActivities: false
  });
```

**Comment by jainshivsagar** [comment] 2024-10-09 06:37
Hi @mjameswh ,
I posted the above data after 3-4 rounds of load testing. After each round of testing, I observed that heap memory utilization was growing incrementally. After the 4th round of testing  & waiting for 5-10 mins, the heap memory utilization didn't come down.

**Comment by mjameswh** [comment] 2024-10-15 18:13
> waiting for 5-10 mins, the heap memory utilization didn't come down.

As I said before, we do not expect a Worker's memory usage to come down once a Workflow has completed. Completed Workflows may still be queried, so caching them may still be beneficial.

What we'd expect is for memory usage to grow until the cache size reaches its maximum capacity (`maxCachedWorkflows`), after which memory usage should remain relatively stable, as less recently used Workflows will get evicted from cache.

> After each round of testing, I observed that heap memory utilization was growing incrementally.

- How many Workflows get started per round?
- What is the capacity of your workflow cache? i.e. `maxCachedWorkflows`? If unsure, look at your Worker Options printed to logs on Worker start.
- Can you please try this with SDK 1.11.2?
- In your heap snapshot, how many instances of `VMWorkflowThreadProxy` do you have? How many instances of `Activity`?

Your screenshot indicates 43'890 instances of `OperatorSubscriber`. That's certainly a lot, yet could still be legitimate, depending on the number of cached Workflows; there are multiple `OperatorSubscriber` per cached Workflows and per pending Activities.

- At which point in your test sequence was your heap snapshot taken?
- By any chance, would it be possible for you to share your heap snapshot file? If you are a Temporal Cloud user, you may open a Zendesk ticket and include the file as a secure attachment.
- Otherwise, could you please try to provide reproduction code that demonstrates this issue?

**Comment by mjameswh** [comment] 2024-11-05 23:38
@jainshivsagar Are you still observing issues, or may we close this ticket?

**Comment by josh-berry** [comment] 2024-12-17 21:33
Closing since we haven't heard back.

**Closed by josh-berry** 2024-12-17 21:33 UTC
Labels: support
