### ISSUE TITLE
[Bug] Issue with Long dependency being listed as devDependency

### ISSUE THREAD

**Issue by brianlu-scale** [temporalio/sdk-typescript#810] opened 2022-08-09 21:24 UTC
### What are you really trying to do?

Trying to get worker deployments to work correctly in a container that uses yarn to only install dependencies, not devDependencies.

### Describe the bug

Running the workers in Docker containers that are built with `yarn workspaces focus --production @packages/temporal-workflows` results in workers that won't execute with the following stack trace:
```
2022-08-04T03:32:56.766Z [ERROR] Failed to activate workflow {
  runId: 'b2fd073b-42a6-40ce-b719-1468474d7f2c',
  error: TypeError: (seconds || long_1.default.UZERO).mul is not a function
      at tsToMs (/opt/app-root/src/.yarn/cache/@temporalio-internal-workflow-common-npm-1.0.0-rc.1-b66f54d7d6-4272b669aa.zip/node_modules/@temporalio/internal-workflow-common/lib/time.js:30:10)
      at /opt/app-root/src/.yarn/cache/@temporalio-worker-npm-1.0.0-rc.1-2998f0d7a7-147819cf17.zip/node_modules/@temporalio/worker/lib/worker.js:664:90
      at async /opt/app-root/src/.yarn/cache/@temporalio-worker-npm-1.0.0-rc.1-2998f0d7a7-147819cf17.zip/node_modules/@temporalio/worker/lib/tracing.js:65:20
      at async /opt/app-root/src/.yarn/cache/@temporalio-worker-npm-1.0.0-rc.1-2998f0d7a7-147819cf17.zip/node_modules/@temporalio/worker/lib/worker.js:593:28,
  workflowExists: false
}
```

However, if we build this instead with `yarn workspaces focus --all @packages/temporal-workflows`, the worker/container works, which implies that some devDependency needs to be listed as a dependency (likely the `long` package).

### Minimal Reproduction

I'm having issues figuring out how to reproduce this or test this to be honest. I tried testing this solution by forking this repository to see if making the suggested changes would fix it but run into errors trying to use the forked repository as my `temporalio` version. I get the following error (https://community.temporal.io/t/fork-temporal-sdk-typescript/5630).

### Environment/Versions

Containers have been built on both M1Macs and Linux machines, using the latest Temporal SDK version. We're using yarn pnp and 3.2.0.

### Additional context

Related to [this forum post](https://community.temporal.io/t/worker-error-with-mul-is-not-a-function/5573)

**Comment by lorensr** [comment] 2022-08-10 03:01
In your stack trace, it's being used inside `internal-workflow-common`, where it's a dependency, not a devDependency, so it should be installed.

https://github.com/temporalio/sdk-typescript/blob/723de0fbc7a04e68084ec99453578e7027eb3803/packages/internal-workflow-common/package.json#L16

When you run without `--production` in the production Docker containers, there's no error?

**Comment by mjameswh** [comment] 2022-08-12 20:31
The problem is that `protobufjs/light` delegates loading of `long` to the `@protobufjs/inquire` package. Now, the `@protobufjs/inquire` itself does not declare a dependency on `long` in its package.json.

This pattern works in most environment, thanks to the way traditional package managers lay out their node_modules directory, but is forbidden by Yarn 3 and PNPM, though the extend to which they goes in applying that restriction depend on various configuration item... Yarn 3's PnP is essentially the strictest of all.

This should be fixed in our next release.

In the mean time, it is possible to fix this locally by adding the following to your .yarnrc.yml file:
```
packageExtensions:
  "@protobufjs/inquire@*":
    dependencies:
      long: "5.2.0"
```

**Closed** 2022-08-12 23:29 UTC
Labels: bug
