### ISSUE TITLE
[Bug] Type Definition Improvement for `ActivityFunction` Interface

### ISSUE THREAD

**Issue by JaredRohe** [temporalio/sdk-typescript#1202] opened 2023-08-13 16:06 UTC
### What are you really trying to do?

I want to use an activity function that does NOT return a promise.   Currently, if I pass the type of a function that is NOT `async` as a type parameter into `proxyActivities` i.e `const {mySyncFunc} =  proxyActivities<typeof mySyncFunc>`, the resulting type of `mySyncFunc` is type `symbol` instead of it's actual function signature type. 

I would like to use `mySyncFunc` as the output of `proxyActivities` without having to type cast, despite the function being synchronous. 

### Describe the bug

When attempting to wrap an activity function with `proxyActivities` the resulting function has type `symbol` if the input function to `proxyActivities` does NOT return a Promise. Typescript warns that `mySyncFunc` is of type `symbol` and therefore may not be callable.  `mySyncFunc` must be type casted before it can be used. 

### Minimal Reproduction
Simply modify the hello world `greet` function to be synchronous i.e: 
![Screenshot 2023-08-13 at 8 59 39 AM](https://github.com/temporalio/sdk-typescript/assets/8333835/b7dc0088-1d3b-4a17-9550-09005407a8b1)

With this change, you will see the Typescript errors when trying to use the `greet` function after passing it into `proxyActivities`.

![Screenshot 2023-08-13 at 8 59 25 AM](https://github.com/temporalio/sdk-typescript/assets/8333835/abd508a6-9268-4412-b448-6e88befdf10c)

### Environment/Versions

- OS and processor: M2 Macbook Pro
- Temporal Version: 1.7.0
- Are you using Docker or Kubernetes or building Temporal from source?: Building from source

### Additional context

It is entirely possible that this is not a bug and it is actually desired that all activity functions be asynchronous.  If that is the case, we can happily close this issue! 

However, if it is indeed the case that activity functions can be both asynchronous and synchronous then this change solves the issue:
![Screenshot 2023-08-13 at 8 57 30 AM](https://github.com/temporalio/sdk-typescript/assets/8333835/89c30671-386e-47b0-9fde-f3620f4c8ede)

The change there is just adding `| R` on line 69 of this file:   https://github.com/temporalio/sdk-typescript/blob/main/packages/common/src/interfaces.ts#L69

**Comment by JaredRohe** [comment] 2023-08-16 17:54
@mjameswh I think this issue will be very quick to address.  Would you mind taking a look?

**Comment by mjameswh** [comment] 2023-08-16 22:46
Thanks @JaredRohe!

This is actually by design, thought that's something that we could reconsider if there's a strong use case for explicitly non-async activities.

May I ask why you are bringing this up?

**Comment by mjameswh** [comment] 2023-08-18 15:43
Closing this ticket since this is not planned.

@JaredRohe I'm still interested to know about your use case for this. We may certainly reconsider if there is a reasonable justification.

**Closed by mjameswh** 2023-08-18 15:43 UTC
Labels: bug

**Comment by JaredRohe** [comment] 2023-08-23 14:29
@mjameswh Sorry for the late response!  I do not have a legit use case here. I ran into this in the process of exploring Temporal and building some toy examples.   I think the design as it is is what we want! =) Thanks for looking into this.
