### ISSUE TITLE
listWorkflowExecutions accept only 1 query params.

### ISSUE THREAD

**Issue by ethanclear** [temporalio/sdk-typescript#1062] opened 2023-02-20 09:27 UTC
### What are you really trying to do?
I'm trying to pass 2 query params with the TS SDK listWorkflowExecutions.

I'm putting only 1 query params then filter it on my side.

### Describe the bug

When adding a params with a "AND" exactly like it should be i'm getting an error
example: WorkflowType = '${name}' AND ExecutionStatus = "Running"

<img width="668" alt="image" src="https://user-images.githubusercontent.com/124141652/220065706-c56e5df5-97a2-4486-84c8-186d607ac549.png">

### The Error.

Error: 2 UNKNOWN: too many filter conditions specified
    at Object.callErrorFromStatus (/Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/node_modules/@temporalio/client/node_modules/@grpc/grpc-js/src/call.ts:81:17)
    at Object.onReceiveStatus (/Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/node_modules/@temporalio/client/node_modules/@grpc/grpc-js/src/client.ts:358:36)
    at /Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/node_modules/@temporalio/client/node_modules/@grpc/grpc-js/src/call-stream.ts:210:27
    at Object.onReceiveStatus (/Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/node_modules/@temporalio/client/src/grpc-retry.ts:176:17)
    at Object.onReceiveStatus (/Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/node_modules/@temporalio/client/node_modules/@grpc/grpc-js/src/client-interceptors.ts:462:34)
    at Object.onReceiveStatus (/Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/node_modules/@temporalio/client/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at /Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/node_modules/@temporalio/client/node_modules/@grpc/grpc-js/src/call-stream.ts:334:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/node_modules/@temporalio/client/node_modules/@grpc/grpc-js/src/client.ts:328:30)
    at Service.rpcImpl (/Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/node_modules/@temporalio/client/src/connection.ts:341:21)
    at Service.rpcCall (/Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/node_modules/protobufjs/src/rpc/service.js:94:21)
    at executor (/Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/node_modules/@protobufjs/aspromise/index.js:44:16)
    at new Promise (<anonymous>)
    at Object.asPromise (/Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/node_modules/@protobufjs/aspromise/index.js:28:12)
    at Service.rpcCall (/Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/node_modules/protobufjs/src/rpc/service.js:86:21)
    at Service.listWorkflowExecutions (eval at Codegen (/Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:4:15)
    at TemporalService.getPendingWorkflowExecutions (/Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/src/temporal.service.ts:25:63)
    at SpecController.getPendingSpecs (/Users/ethansayagh/Desktop/DEV/work/clear/cal/catalog-service/src/spec/spec.controller.ts:17:57) {
  code: 2,
  details: 'too many filter conditions specified',
  metadata: Metadata {
    internalRepr: Map(1) { 'content-type' => [Array] },
    options: {}
  }

**Comment by bergundy** [comment] 2023-02-20 16:25
Hi, I’m not sure I understand exactly what the problem is.
What error are you getting?

Side note: there’s a friendlier API for listing workflows, it won’t help your issue though.

https://typescript.temporal.io/api/classes/client.WorkflowClient#list

https://github.com/temporalio/samples-typescript/blob/ba6208155bc7b547c76931b7e14e92ce4594af28/food-delivery/apps/driver/pages/api/%5Btrpc%5D.ts#L19

**Comment by ethanclear** [comment] 2023-02-21 08:25
Updated

**Comment by ethanclear** [comment] 2023-02-21 09:08
Using the list method you gave me i get the same error: 2 UNKNOWN: too many filter conditions specified

**Comment by mjameswh** [comment] 2023-02-21 12:09
That error message indicates that your temporal server is using a persistance backend that do not support queries containing two filter predicates.

How is your temporal server deployed, which version, and which persistance backend are you using?

**Comment by mjameswh** [comment] 2023-03-01 19:04
@ethanclear Is this resolved?

**Comment by bergundy** [comment] 2023-03-09 00:16
I'm closing this, please reopen if you feel this isn't resolved.

**Closed by bergundy** 2023-03-09 00:16 UTC
Labels: support
